USE [DevTools]
GO
/****** Object:  Table [ACAOUSUARIO]    Script Date: 20/04/2023 10:45:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [ACAOUSUARIO](
	[CODIGO] [int] NOT NULL,
	[CODIGOUSUARIO] [int] NOT NULL,
	[ACAO] [varchar](200) NOT NULL,
	[DATAREGISTRO] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [ANEXORESPOSTA]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [ANEXORESPOSTA](
	[CODIGO] [int] NOT NULL,
	[CODIGOQUESTAO] [int] NOT NULL,
	[DATAREGISTRO] [datetime] NOT NULL,
	[ANEXO] [varbinary](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [ANEXOSQUESTOES]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [ANEXOSQUESTOES](
	[CODIGO] [int] NOT NULL,
	[CODIGOQUESTAO] [int] NOT NULL,
	[DATAREGISTRO] [datetime] NOT NULL,
	[ANEXO] [varbinary](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [APRESENTACAO]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [APRESENTACAO](
	[APRESENTACAO] [char](1) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[APRESENTACAO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [AUTOMATICO]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [AUTOMATICO](
	[AUTOMATICO] [char](1) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[AUTOMATICO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [BIOMAS]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [BIOMAS](
	[ID] [int] NOT NULL,
	[NOME] [varchar](200) NULL,
	[DISTRIBUICAO] [varchar](200) NULL,
	[CARACTERISTICAS] [varchar](8000) NULL,
	[FITOFISIONOMIA] [varchar](8000) NULL,
	[OBSERVACAO] [varchar](8000) NULL,
	[IDUSUARIO] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [CAMPOS]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [CAMPOS](
	[CODIGO] [int] NOT NULL,
	[CODIGOTABELA] [int] NOT NULL,
	[NOME] [varchar](50) NOT NULL,
	[CHAVE] [char](1) NOT NULL,
	[DOMINIO] [varchar](100) NOT NULL,
	[CODIGOTIPO] [int] NOT NULL,
	[NAONULO] [char](1) NOT NULL,
	[UNICO] [char](1) NOT NULL,
	[CHECAR] [varchar](300) NOT NULL,
	[PADRAO] [varchar](300) NOT NULL,
	[COMENTARIO] [varchar](900) NOT NULL,
	[TAMANHO] [int] NOT NULL,
	[PRECISAO] [decimal](15, 4) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC,
	[CODIGOTABELA] ASC,
	[NOME] ASC,
	[CHAVE] ASC,
	[DOMINIO] ASC,
	[CODIGOTIPO] ASC,
	[NAONULO] ASC,
	[UNICO] ASC,
	[CHECAR] ASC,
	[PADRAO] ASC,
	[COMENTARIO] ASC,
	[TAMANHO] ASC,
	[PRECISAO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [CARTAOCREDITODEVTOOLS]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [CARTAOCREDITODEVTOOLS](
	[NUMEROCARTAO] [varchar](100) NOT NULL,
	[DATAVALIDADE] [varchar](50) NOT NULL,
	[CODIGOSEGURANCA] [char](3) NOT NULL,
	[CREATED] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[NUMEROCARTAO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [CHAVESJWT]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [CHAVESJWT](
	[CHAVE] [char](60) NOT NULL,
	[DATAINSERCAO] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[CHAVE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [CLIENTES]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [CLIENTES](
	[CODIGO] [int] NOT NULL,
	[RAZAOSOCIAL] [varchar](1000) NOT NULL,
	[NOMEFANTASIA] [varchar](1000) NOT NULL,
	[CNPJ] [char](18) NOT NULL,
	[CIDADE] [varchar](500) NOT NULL,
	[ESTADO] [char](2) NOT NULL,
	[ENDERECO] [varchar](1000) NOT NULL,
	[CEP] [varchar](8) NOT NULL,
	[EMAIL] [char](500) NOT NULL,
	[TELEFONE] [varchar](30) NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [CODIGOS_TABLE]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [CODIGOS_TABLE](
	[TABELA] [varchar](30) NOT NULL,
	[CODIGO] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[TABELA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [CONFIGURACAOEMAIL]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [CONFIGURACAOEMAIL](
	[CODIGO] [int] NOT NULL,
	[EMAILREMETENTE] [varchar](300) NOT NULL,
	[SMTPCLIENT] [varchar](100) NULL,
	[PORTA] [int] NOT NULL,
	[EMAILCREDENCIAL] [varchar](300) NOT NULL,
	[SENHACREDENCIAL] [varchar](200) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [CONSULTAS]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [CONSULTAS](
	[CODIGO] [int] NOT NULL,
	[NOMECONSULTA] [varchar](100) NOT NULL,
	[CONSULTA] [varchar](4000) NOT NULL,
	[CREATED] [varchar](20) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [CONTABANCOFORDEV]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [CONTABANCOFORDEV](
	[CREATED] [varchar](50) NOT NULL,
	[CONTACORRENTE] [varchar](100) NOT NULL,
	[AGENCIA] [varchar](50) NOT NULL,
	[BANCO] [varchar](50) NOT NULL,
	[CIDADE] [varchar](150) NOT NULL,
	[ESTADO] [char](2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CONTACORRENTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [CRUDFORMSINSTALADOR]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [CRUDFORMSINSTALADOR](
	[CODIGO] [int] NOT NULL,
	[VERSAO] [varchar](10) NOT NULL,
	[CREATED] [datetime] NOT NULL,
	[DIRETORIO] [varchar](300) NOT NULL,
	[ATIVO] [varchar](1) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [DESPESAS]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [DESPESAS](
	[CODIGO] [int] NOT NULL,
	[DATAINSERCAO] [datetime] NOT NULL,
	[DATADESPESA] [varchar](30) NOT NULL,
	[DESCRICAO] [varchar](300) NOT NULL,
	[CATEGORIA] [varchar](30) NOT NULL,
	[VALOR] [varchar](30) NOT NULL,
	[CONTA] [varchar](300) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [EMAIL]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [EMAIL](
	[CODIGO] [int] NOT NULL,
	[DESTINATARIO] [varchar](300) NOT NULL,
	[ASSUNTO] [varchar](300) NOT NULL,
	[TEXTO] [varbinary](max) NULL,
	[DATAENVIO] [datetime] NOT NULL,
	[STATUS] [char](1) NOT NULL,
	[OBSERVACAO] [varchar](1000) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [EMAILANEXOS]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [EMAILANEXOS](
	[CODIGO] [int] NOT NULL,
	[CODIGOEMAIL] [int] NOT NULL,
	[ARQUIVO] [varbinary](1) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [EMAILBackup]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [EMAILBackup](
	[CODIGO] [int] NOT NULL,
	[DESTINATARIO] [varchar](300) NOT NULL,
	[ASSUNTO] [varchar](300) NOT NULL,
	[TEXTO] [varchar](8000) NOT NULL,
	[DATAENVIO] [datetime] NOT NULL,
	[STATUS] [char](1) NOT NULL,
	[OBSERVACAO] [varchar](1000) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [EMPRESAFORDEV]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [EMPRESAFORDEV](
	[NOME] [varchar](200) NULL,
	[CNPJ] [varchar](15) NOT NULL,
	[IE] [varchar](50) NOT NULL,
	[DATAABERTURA] [varchar](12) NOT NULL,
	[SITE] [varchar](500) NOT NULL,
	[EMAIL] [varchar](500) NOT NULL,
	[CEP] [varchar](10) NOT NULL,
	[ENDERECO] [varchar](100) NOT NULL,
	[NUMERO] [varchar](20) NOT NULL,
	[BAIRRO] [varchar](500) NOT NULL,
	[CIDADE] [varchar](500) NOT NULL,
	[ESTADO] [char](3) NOT NULL,
	[TELEFONEFIXO] [varchar](30) NOT NULL,
	[CELULAR] [varchar](30) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CNPJ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [IMAGENSBIOMA]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [IMAGENSBIOMA](
	[ID] [int] NOT NULL,
	[IDBIOMA] [int] NOT NULL,
	[CAMINHO] [varchar](300) NULL,
	[IDUSUARIO] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [IMAGENSPLANTA]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [IMAGENSPLANTA](
	[ID] [int] NOT NULL,
	[IDPLANTA] [int] NOT NULL,
	[CAMINHO] [varchar](300) NULL,
	[IDUSUARIO] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [LOGG]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [LOGG](
	[TIPO_LOG] [char](1) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[TIPO_LOG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [MODULOS]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MODULOS](
	[CODIGO] [int] NOT NULL,
	[NOMEMODULO] [varchar](100) NOT NULL,
	[DESCRICAO] [varchar](1000) NULL,
	[SEQUENCIAABERTURA] [varchar](1000) NULL,
	[CODIGOPROJETO] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC,
	[CODIGOPROJETO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [OLEOSESSENCIAIS]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [OLEOSESSENCIAIS](
	[CODIGO] [int] NOT NULL,
	[CODIGOPRODUTO] [varchar](20) NULL,
	[NOME] [varchar](300) NOT NULL,
	[TAMANHO] [varchar](50) NULL,
	[PRECOREGULAR] [varchar](50) NULL,
	[PRECOMEMBROS] [varchar](50) NULL,
	[PV] [varchar](20) NOT NULL,
	[MODOUSAR] [varchar](4000) NULL,
	[DESCRICAO] [varchar](4000) NULL,
	[PALAVRASCHAVES] [varchar](4000) NOT NULL,
	[COR] [varchar](300) NULL,
	[BENEFICIOSPRIMARIOS] [varchar](4000) NOT NULL,
	[DESCRICAOAROMATICA] [varchar](4000) NOT NULL,
	[METODOEXTRACAO] [varchar](4000) NULL,
	[PARTEPLANTA] [varchar](1000) NULL,
	[COMPONENTESQUIMICOS] [varchar](1000) NULL,
	[USOS] [varchar](4000) NULL,
	[PRECAUCOES] [varchar](4000) NULL,
	[TIPOPRODUTO] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [PALAVRAS]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PALAVRAS](
	[ID] [int] NOT NULL,
	[NIVEL] [int] NOT NULL,
	[PALAVRA] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[PALAVRA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [PARAMETROS]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PARAMETROS](
	[CHAVE] [varchar](50) NOT NULL,
	[VALOR] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CHAVE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [PESSOASFORDEV]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PESSOASFORDEV](
	[NOME] [varchar](2000) NOT NULL,
	[IDADE] [int] NOT NULL,
	[CPF] [varchar](12) NOT NULL,
	[RG] [varchar](12) NOT NULL,
	[DATANASCIMENTO] [varchar](10) NOT NULL,
	[SEXO] [varchar](20) NOT NULL,
	[SIGNO] [varchar](30) NOT NULL,
	[MAE] [varchar](2000) NOT NULL,
	[PAI] [varchar](2000) NOT NULL,
	[EMAIL] [varchar](500) NOT NULL,
	[SENHA] [varchar](50) NOT NULL,
	[CEP] [varchar](8) NOT NULL,
	[ENDERECO] [varchar](1000) NOT NULL,
	[NUMERO] [int] NOT NULL,
	[BAIRRO] [varchar](500) NOT NULL,
	[CIDADE] [varchar](1000) NOT NULL,
	[ESTADO] [char](2) NOT NULL,
	[TELEFONEFIXO] [varchar](50) NOT NULL,
	[CELULAR] [varchar](50) NOT NULL,
	[ALTURA] [varchar](10) NOT NULL,
	[PESO] [int] NOT NULL,
	[TIPOSANGUINEO] [varchar](3) NOT NULL,
	[CORFAVORITA] [varchar](30) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CPF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [PLANTAS]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PLANTAS](
	[ID] [int] NOT NULL,
	[IDBIOMA] [int] NOT NULL,
	[NOMECIENTIFICO] [varchar](200) NULL,
	[NOMEPOPULAR] [varchar](200) NULL,
	[HABITATE] [varchar](1000) NULL,
	[FOLHA] [varchar](8000) NULL,
	[FLOR] [varchar](8000) NULL,
	[FRUTO] [varchar](8000) NULL,
	[FAMILIA] [varchar](200) NULL,
	[TRIBO] [varchar](200) NULL,
	[IDUSUARIO] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [PROJETO]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PROJETO](
	[CODIGO] [int] NOT NULL,
	[NOME] [varchar](50) NOT NULL,
	[DESCRICAO] [varchar](400) NULL,
	[STATUS] [char](1) NULL,
	[GIT] [varchar](200) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [PROVA]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PROVA](
	[CODIGO] [int] NOT NULL,
	[NOMEPROVA] [varchar](500) NOT NULL,
	[LOCAL] [varchar](500) NOT NULL,
	[TIPOPROVA] [varchar](100) NOT NULL,
	[DATAAPLICACAO] [varchar](10) NOT NULL,
	[OBSERVACAOPROVA] [varchar](3000) NULL,
	[OBSERVACAOGABARITO] [varchar](2000) NOT NULL,
	[DATAREGISTRO] [datetime] NOT NULL,
	[BANCA] [varchar](1000) NULL,
	[LinkProva] [varchar](300) NULL,
	[LinkGabarito] [varchar](300) NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [QUESTOES]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [QUESTOES](
	[CODIGO] [int] NOT NULL,
	[DATAREGISTRO] [datetime] NOT NULL,
	[CAMPOQUESTAO] [varchar](8000) NOT NULL,
	[OBSERVACAOQUESTAO] [varchar](8000) NOT NULL,
	[MATERIA] [varchar](300) NOT NULL,
	[CODIGOPROVA] [int] NOT NULL,
	[NUMEROQUESTAO] [varchar](20) NULL,
	[ativo] [char](1) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [RECEITAS]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [RECEITAS](
	[CODIGO] [int] NOT NULL,
	[DATAREGISTRO] [datetime] NOT NULL,
	[DATATRANSACAO] [varchar](30) NOT NULL,
	[DESCRICAO] [varchar](300) NOT NULL,
	[CATEGORIA] [varchar](300) NOT NULL,
	[VALOR] [varchar](30) NOT NULL,
	[CONTA] [varchar](300) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [RECUPERASENHACONCURSANDO]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [RECUPERASENHACONCURSANDO](
	[CODIGO] [int] NOT NULL,
	[DATAREGISTRO] [datetime] NOT NULL,
	[GUID] [varchar](64) NOT NULL,
	[EMAIL] [varchar](300) NOT NULL,
	[RECUPERADO] [char](1) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [RECUPERASENHACRUDFORMS]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [RECUPERASENHACRUDFORMS](
	[codigo] [int] NOT NULL,
	[created] [datetime] NOT NULL,
	[guid] [varchar](64) NULL,
	[email] [varchar](300) NULL,
	[recuperado] [char](1) NOT NULL,
	[updated] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[codigo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [RELACAO]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [RELACAO](
	[CODIGO] [int] NOT NULL,
	[CODIGOPROJETO] [int] NOT NULL,
	[TABELAORIGEM] [int] NOT NULL,
	[CAMPOORIGEM] [int] NOT NULL,
	[TABELADESTINO] [int] NOT NULL,
	[CAMPODESTINO] [int] NOT NULL,
	[CARDINALIDADEORIGEM] [varchar](1) NOT NULL,
	[CARDINALIDADEDESTINO] [varchar](1) NOT NULL,
	[FOREINGKEY] [varchar](200) NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [RESPOSTASQUESTOES]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [RESPOSTASQUESTOES](
	[CODIGO] [int] NOT NULL,
	[CODIGOQUESTAO] [int] NOT NULL,
	[DATAREGISTRO] [datetime] NOT NULL,
	[TEXTORESPOSTA] [varchar](8000) NOT NULL,
	[CERTA] [char](1) NOT NULL,
	[OBSERVACAORESPOSTA] [varchar](8000) NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [RESPOSTASUSUARIOS]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [RESPOSTASUSUARIOS](
	[CODIGO] [int] NOT NULL,
	[CODIGOUSUARIO] [int] NOT NULL,
	[CODIGORESPOSTA] [int] NOT NULL,
	[DATARESPOSTA] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [RESULTADOS]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [RESULTADOS](
	[NOME] [varchar](100) NOT NULL,
	[TEMPO] [varchar](20) NOT NULL,
	[NUMEROACERTOS] [varchar](10) NOT NULL,
	[DATAINSERCAO] [varchar](20) NULL,
	[TIPO] [varchar](100) NOT NULL,
	[NumeroQuestoes] [int] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [RESULTADOSSOLETRANDO]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [RESULTADOSSOLETRANDO](
	[ID] [int] NOT NULL,
	[NOME] [varchar](100) NOT NULL,
	[NUMEROACERTOS] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [TABELA]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [TABELA](
	[CODIGO] [int] NOT NULL,
	[PROJETO] [int] NOT NULL,
	[NOME] [varchar](50) NOT NULL,
	[DESCRICAO] [varchar](400) NULL,
	[NOTAS] [varchar](400) NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC,
	[PROJETO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [TABELAS]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [TABELAS](
	[TAB] [varchar](40) NOT NULL,
	[FIELD] [varchar](25) NOT NULL,
	[TYPE] [char](1) NOT NULL,
	[SIZE] [int] NOT NULL,
	[PREC] [int] NOT NULL,
	[FLAG] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[TAB] ASC,
	[FIELD] ASC,
	[TYPE] ASC,
	[SIZE] ASC,
	[PREC] ASC,
	[FLAG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [TABELASMODULOS]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [TABELASMODULOS](
	[CODIGOTABELA] [int] NOT NULL,
	[CODIGOCAMPO] [int] NOT NULL,
	[CODIGOMODULO] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGOTABELA] ASC,
	[CODIGOCAMPO] ASC,
	[CODIGOMODULO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [temp1]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [temp1](
	[teste] [varbinary](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [TESTE]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [TESTE](
	[TESTECAMPO] [varchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [TIPOCAMPO]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [TIPOCAMPO](
	[CODIGO] [int] NOT NULL,
	[NOME] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC,
	[NOME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [TIPOSUPORTE]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [TIPOSUPORTE](
	[CODIGO] [int] NOT NULL,
	[DESCRICAO] [varchar](1000) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [TRADUCOES]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [TRADUCOES](
	[CODIGO] [int] NOT NULL,
	[DATAREGISTRO] [datetime] NOT NULL,
	[PALAVRAPORTUGUES] [varchar](300) NOT NULL,
	[PALAVRAINGLES] [varchar](300) NOT NULL,
	[CLASSEGRAMATICAL] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [USUARIOCONCURSANDO]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [USUARIOCONCURSANDO](
	[CODIGO] [int] NOT NULL,
	[DATANASCIMENTO] [date] NOT NULL,
	[EMAIL] [varchar](300) NOT NULL,
	[NOME] [varchar](200) NOT NULL,
	[PASSWORD] [varchar](100) NOT NULL,
	[ADMIN] [char](1) NOT NULL,
	[created] [datetime] NOT NULL,
	[BOT] [char](1) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [USUARIOS]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [USUARIOS](
	[ID] [int] NOT NULL,
	[LOGIN] [varchar](50) NOT NULL,
	[PASS] [varchar](12) NOT NULL,
	[NOME] [varchar](50) NOT NULL,
	[Email] [varchar](300) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[LOGIN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [USUARIOSCRUDFORMS]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [USUARIOSCRUDFORMS](
	[CODIGO] [int] NOT NULL,
	[LOGIN] [varchar](50) NOT NULL,
	[SENHA] [varchar](20) NOT NULL,
	[ADMINISTRADOR] [char](1) NOT NULL,
	[DESENVOLVEDOR] [char](1) NOT NULL,
	[EMAIL] [varchar](200) NOT NULL,
	[USUARIOPAI] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [VEICULOSFORDEV]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [VEICULOSFORDEV](
	[MARCA] [varchar](300) NOT NULL,
	[MODELO] [varchar](300) NOT NULL,
	[ANO] [varchar](10) NOT NULL,
	[RENAVAM] [varchar](30) NOT NULL,
	[PLACAVEICULO] [varchar](20) NOT NULL,
	[COR] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RENAVAM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [VERBOCONJUGADO]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [VERBOCONJUGADO](
	[CODIGO] [int] NOT NULL,
	[DATACRIACAO] [datetime] NOT NULL,
	[VERBO] [varchar](500) NOT NULL,
	[PRESENTE] [varchar](500) NOT NULL,
	[PRETERITOIMPERFEITO] [varchar](500) NOT NULL,
	[PRETERITOPERFEITO] [varchar](500) NOT NULL,
	[PRETERITOMAISQUEPERFEITO] [varchar](500) NOT NULL,
	[FUTURODOPRESENTE] [varchar](500) NOT NULL,
	[FUTURODOPRETERITO] [varchar](500) NOT NULL,
	[PRONOME] [varchar](30) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [VERBOS]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [VERBOS](
	[CODIGO] [int] NOT NULL,
	[PALAVRA] [varchar](500) NOT NULL,
	[DATAINSERCAO] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [VERSAO]    Script Date: 20/04/2023 10:45:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [VERSAO](
	[DERCREATOR] [varchar](10) NULL
) ON [PRIMARY]
GO
ALTER TABLE [ACAOUSUARIO] ADD  DEFAULT ((0)) FOR [CODIGOUSUARIO]
GO
ALTER TABLE [ACAOUSUARIO] ADD  DEFAULT ('') FOR [ACAO]
GO
ALTER TABLE [ANEXORESPOSTA] ADD  DEFAULT ((0)) FOR [CODIGOQUESTAO]
GO
ALTER TABLE [ANEXORESPOSTA] ADD  DEFAULT ('') FOR [DATAREGISTRO]
GO
ALTER TABLE [ANEXOSQUESTOES] ADD  DEFAULT ((0)) FOR [CODIGOQUESTAO]
GO
ALTER TABLE [ANEXOSQUESTOES] ADD  DEFAULT ('') FOR [DATAREGISTRO]
GO
ALTER TABLE [APRESENTACAO] ADD  DEFAULT ('0') FOR [APRESENTACAO]
GO
ALTER TABLE [AUTOMATICO] ADD  DEFAULT ('0') FOR [AUTOMATICO]
GO
ALTER TABLE [CAMPOS] ADD  DEFAULT ((0)) FOR [CODIGO]
GO
ALTER TABLE [CAMPOS] ADD  DEFAULT ((0)) FOR [CODIGOTABELA]
GO
ALTER TABLE [CAMPOS] ADD  DEFAULT ('') FOR [NOME]
GO
ALTER TABLE [CAMPOS] ADD  DEFAULT ('0') FOR [CHAVE]
GO
ALTER TABLE [CAMPOS] ADD  DEFAULT ('') FOR [DOMINIO]
GO
ALTER TABLE [CAMPOS] ADD  DEFAULT ((0)) FOR [CODIGOTIPO]
GO
ALTER TABLE [CAMPOS] ADD  DEFAULT ('0') FOR [NAONULO]
GO
ALTER TABLE [CAMPOS] ADD  DEFAULT ('0') FOR [UNICO]
GO
ALTER TABLE [CAMPOS] ADD  DEFAULT ('') FOR [CHECAR]
GO
ALTER TABLE [CAMPOS] ADD  DEFAULT ('') FOR [PADRAO]
GO
ALTER TABLE [CAMPOS] ADD  DEFAULT ('') FOR [COMENTARIO]
GO
ALTER TABLE [CAMPOS] ADD  DEFAULT ((0)) FOR [TAMANHO]
GO
ALTER TABLE [CAMPOS] ADD  DEFAULT ((0)) FOR [PRECISAO]
GO
ALTER TABLE [CARTAOCREDITODEVTOOLS] ADD  DEFAULT ('') FOR [NUMEROCARTAO]
GO
ALTER TABLE [CARTAOCREDITODEVTOOLS] ADD  DEFAULT ('') FOR [DATAVALIDADE]
GO
ALTER TABLE [CARTAOCREDITODEVTOOLS] ADD  DEFAULT ('') FOR [CODIGOSEGURANCA]
GO
ALTER TABLE [CARTAOCREDITODEVTOOLS] ADD  DEFAULT ('') FOR [CREATED]
GO
ALTER TABLE [CLIENTES] ADD  DEFAULT ((0)) FOR [CODIGO]
GO
ALTER TABLE [CLIENTES] ADD  DEFAULT ('') FOR [RAZAOSOCIAL]
GO
ALTER TABLE [CLIENTES] ADD  DEFAULT ('') FOR [NOMEFANTASIA]
GO
ALTER TABLE [CLIENTES] ADD  DEFAULT ('') FOR [CNPJ]
GO
ALTER TABLE [CLIENTES] ADD  DEFAULT ('') FOR [CIDADE]
GO
ALTER TABLE [CLIENTES] ADD  DEFAULT ('') FOR [ESTADO]
GO
ALTER TABLE [CLIENTES] ADD  DEFAULT ('') FOR [ENDERECO]
GO
ALTER TABLE [CLIENTES] ADD  DEFAULT ('') FOR [CEP]
GO
ALTER TABLE [CLIENTES] ADD  DEFAULT ('') FOR [EMAIL]
GO
ALTER TABLE [CODIGOS_TABLE] ADD  DEFAULT ((0)) FOR [CODIGO]
GO
ALTER TABLE [CONFIGURACAOEMAIL] ADD  DEFAULT ('') FOR [EMAILREMETENTE]
GO
ALTER TABLE [CONFIGURACAOEMAIL] ADD  DEFAULT ((587)) FOR [PORTA]
GO
ALTER TABLE [CONFIGURACAOEMAIL] ADD  DEFAULT ('') FOR [EMAILCREDENCIAL]
GO
ALTER TABLE [CONFIGURACAOEMAIL] ADD  DEFAULT ('') FOR [SENHACREDENCIAL]
GO
ALTER TABLE [CONSULTAS] ADD  DEFAULT ('') FOR [NOMECONSULTA]
GO
ALTER TABLE [CONSULTAS] ADD  DEFAULT ('') FOR [CONSULTA]
GO
ALTER TABLE [CONSULTAS] ADD  DEFAULT ('') FOR [CREATED]
GO
ALTER TABLE [CONTABANCOFORDEV] ADD  DEFAULT ('') FOR [CREATED]
GO
ALTER TABLE [CONTABANCOFORDEV] ADD  DEFAULT ('') FOR [CONTACORRENTE]
GO
ALTER TABLE [CONTABANCOFORDEV] ADD  DEFAULT ('') FOR [AGENCIA]
GO
ALTER TABLE [CONTABANCOFORDEV] ADD  DEFAULT ('') FOR [BANCO]
GO
ALTER TABLE [CONTABANCOFORDEV] ADD  DEFAULT ('') FOR [CIDADE]
GO
ALTER TABLE [CONTABANCOFORDEV] ADD  DEFAULT ('') FOR [ESTADO]
GO
ALTER TABLE [CRUDFORMSINSTALADOR] ADD  DEFAULT ('') FOR [VERSAO]
GO
ALTER TABLE [CRUDFORMSINSTALADOR] ADD  DEFAULT (((2022)-(12))-(20)) FOR [CREATED]
GO
ALTER TABLE [CRUDFORMSINSTALADOR] ADD  DEFAULT ('') FOR [DIRETORIO]
GO
ALTER TABLE [CRUDFORMSINSTALADOR] ADD  DEFAULT ('1') FOR [ATIVO]
GO
ALTER TABLE [DESPESAS] ADD  DEFAULT ('') FOR [DATADESPESA]
GO
ALTER TABLE [DESPESAS] ADD  DEFAULT ('') FOR [DESCRICAO]
GO
ALTER TABLE [DESPESAS] ADD  DEFAULT ('') FOR [CATEGORIA]
GO
ALTER TABLE [DESPESAS] ADD  DEFAULT ('') FOR [VALOR]
GO
ALTER TABLE [DESPESAS] ADD  DEFAULT ('') FOR [CONTA]
GO
ALTER TABLE [EMAIL] ADD  DEFAULT ('') FOR [DESTINATARIO]
GO
ALTER TABLE [EMAIL] ADD  DEFAULT ('') FOR [ASSUNTO]
GO
ALTER TABLE [EMAIL] ADD  DEFAULT ('0') FOR [STATUS]
GO
ALTER TABLE [EMAILANEXOS] ADD  DEFAULT ((0)) FOR [CODIGOEMAIL]
GO
ALTER TABLE [EMPRESAFORDEV] ADD  DEFAULT ('') FOR [CNPJ]
GO
ALTER TABLE [EMPRESAFORDEV] ADD  DEFAULT ('') FOR [IE]
GO
ALTER TABLE [EMPRESAFORDEV] ADD  DEFAULT ('') FOR [DATAABERTURA]
GO
ALTER TABLE [EMPRESAFORDEV] ADD  DEFAULT ('') FOR [SITE]
GO
ALTER TABLE [EMPRESAFORDEV] ADD  DEFAULT ('') FOR [EMAIL]
GO
ALTER TABLE [EMPRESAFORDEV] ADD  DEFAULT ('') FOR [CEP]
GO
ALTER TABLE [EMPRESAFORDEV] ADD  DEFAULT ('') FOR [ENDERECO]
GO
ALTER TABLE [EMPRESAFORDEV] ADD  DEFAULT ('') FOR [NUMERO]
GO
ALTER TABLE [EMPRESAFORDEV] ADD  DEFAULT ('') FOR [BAIRRO]
GO
ALTER TABLE [EMPRESAFORDEV] ADD  DEFAULT ('') FOR [CIDADE]
GO
ALTER TABLE [EMPRESAFORDEV] ADD  DEFAULT ('SP') FOR [ESTADO]
GO
ALTER TABLE [EMPRESAFORDEV] ADD  DEFAULT ('') FOR [TELEFONEFIXO]
GO
ALTER TABLE [EMPRESAFORDEV] ADD  DEFAULT ('') FOR [CELULAR]
GO
ALTER TABLE [LOGG] ADD  DEFAULT ('0') FOR [TIPO_LOG]
GO
ALTER TABLE [MODULOS] ADD  DEFAULT ((0)) FOR [CODIGO]
GO
ALTER TABLE [MODULOS] ADD  DEFAULT ('') FOR [NOMEMODULO]
GO
ALTER TABLE [MODULOS] ADD  DEFAULT ((0)) FOR [CODIGOPROJETO]
GO
ALTER TABLE [OLEOSESSENCIAIS] ADD  DEFAULT ('') FOR [NOME]
GO
ALTER TABLE [OLEOSESSENCIAIS] ADD  DEFAULT ('') FOR [PV]
GO
ALTER TABLE [OLEOSESSENCIAIS] ADD  DEFAULT ('') FOR [PALAVRASCHAVES]
GO
ALTER TABLE [OLEOSESSENCIAIS] ADD  DEFAULT ('') FOR [BENEFICIOSPRIMARIOS]
GO
ALTER TABLE [OLEOSESSENCIAIS] ADD  DEFAULT ('') FOR [DESCRICAOAROMATICA]
GO
ALTER TABLE [OLEOSESSENCIAIS] ADD  DEFAULT ('OLEO') FOR [TIPOPRODUTO]
GO
ALTER TABLE [PARAMETROS] ADD  DEFAULT ('0') FOR [CHAVE]
GO
ALTER TABLE [PARAMETROS] ADD  DEFAULT ('') FOR [VALOR]
GO
ALTER TABLE [PESSOASFORDEV] ADD  DEFAULT ('') FOR [NOME]
GO
ALTER TABLE [PESSOASFORDEV] ADD  DEFAULT ((0)) FOR [IDADE]
GO
ALTER TABLE [PESSOASFORDEV] ADD  DEFAULT ('') FOR [CPF]
GO
ALTER TABLE [PESSOASFORDEV] ADD  DEFAULT ('') FOR [RG]
GO
ALTER TABLE [PESSOASFORDEV] ADD  DEFAULT ('') FOR [DATANASCIMENTO]
GO
ALTER TABLE [PESSOASFORDEV] ADD  DEFAULT ('Masculino') FOR [SEXO]
GO
ALTER TABLE [PESSOASFORDEV] ADD  DEFAULT ('') FOR [SIGNO]
GO
ALTER TABLE [PESSOASFORDEV] ADD  DEFAULT ('') FOR [MAE]
GO
ALTER TABLE [PESSOASFORDEV] ADD  DEFAULT ('') FOR [PAI]
GO
ALTER TABLE [PESSOASFORDEV] ADD  DEFAULT ('') FOR [EMAIL]
GO
ALTER TABLE [PESSOASFORDEV] ADD  DEFAULT ('') FOR [SENHA]
GO
ALTER TABLE [PESSOASFORDEV] ADD  DEFAULT ('') FOR [CEP]
GO
ALTER TABLE [PESSOASFORDEV] ADD  DEFAULT ('') FOR [ENDERECO]
GO
ALTER TABLE [PESSOASFORDEV] ADD  DEFAULT ((0)) FOR [NUMERO]
GO
ALTER TABLE [PESSOASFORDEV] ADD  DEFAULT ('') FOR [BAIRRO]
GO
ALTER TABLE [PESSOASFORDEV] ADD  DEFAULT ('') FOR [CIDADE]
GO
ALTER TABLE [PESSOASFORDEV] ADD  DEFAULT ('MG') FOR [ESTADO]
GO
ALTER TABLE [PESSOASFORDEV] ADD  DEFAULT ('') FOR [TELEFONEFIXO]
GO
ALTER TABLE [PESSOASFORDEV] ADD  DEFAULT ('') FOR [CELULAR]
GO
ALTER TABLE [PESSOASFORDEV] ADD  DEFAULT ('') FOR [ALTURA]
GO
ALTER TABLE [PESSOASFORDEV] ADD  DEFAULT ((0)) FOR [PESO]
GO
ALTER TABLE [PESSOASFORDEV] ADD  DEFAULT ('') FOR [TIPOSANGUINEO]
GO
ALTER TABLE [PESSOASFORDEV] ADD  DEFAULT ('') FOR [CORFAVORITA]
GO
ALTER TABLE [PROJETO] ADD  DEFAULT ((0)) FOR [CODIGO]
GO
ALTER TABLE [PROJETO] ADD  DEFAULT ('') FOR [NOME]
GO
ALTER TABLE [PROJETO] ADD  DEFAULT ('-') FOR [GIT]
GO
ALTER TABLE [PROVA] ADD  DEFAULT ('') FOR [NOMEPROVA]
GO
ALTER TABLE [PROVA] ADD  DEFAULT ('') FOR [LOCAL]
GO
ALTER TABLE [PROVA] ADD  DEFAULT ('') FOR [TIPOPROVA]
GO
ALTER TABLE [PROVA] ADD  DEFAULT ('') FOR [DATAAPLICACAO]
GO
ALTER TABLE [PROVA] ADD  DEFAULT ('') FOR [OBSERVACAOGABARITO]
GO
ALTER TABLE [QUESTOES] ADD  DEFAULT ('') FOR [CAMPOQUESTAO]
GO
ALTER TABLE [QUESTOES] ADD  DEFAULT ('') FOR [OBSERVACAOQUESTAO]
GO
ALTER TABLE [QUESTOES] ADD  DEFAULT ('') FOR [MATERIA]
GO
ALTER TABLE [QUESTOES] ADD  DEFAULT ((0)) FOR [CODIGOPROVA]
GO
ALTER TABLE [QUESTOES] ADD  DEFAULT ('1') FOR [ativo]
GO
ALTER TABLE [RECEITAS] ADD  DEFAULT ('') FOR [DATATRANSACAO]
GO
ALTER TABLE [RECEITAS] ADD  DEFAULT ('') FOR [DESCRICAO]
GO
ALTER TABLE [RECEITAS] ADD  DEFAULT ('') FOR [CATEGORIA]
GO
ALTER TABLE [RECEITAS] ADD  DEFAULT ('') FOR [VALOR]
GO
ALTER TABLE [RECEITAS] ADD  DEFAULT ('') FOR [CONTA]
GO
ALTER TABLE [RECUPERASENHACONCURSANDO] ADD  DEFAULT ('') FOR [GUID]
GO
ALTER TABLE [RECUPERASENHACONCURSANDO] ADD  DEFAULT ('') FOR [EMAIL]
GO
ALTER TABLE [RECUPERASENHACONCURSANDO] ADD  DEFAULT ('0') FOR [RECUPERADO]
GO
ALTER TABLE [RECUPERASENHACRUDFORMS] ADD  DEFAULT ('0') FOR [recuperado]
GO
ALTER TABLE [RELACAO] ADD  DEFAULT ((0)) FOR [CODIGO]
GO
ALTER TABLE [RELACAO] ADD  DEFAULT ((0)) FOR [CODIGOPROJETO]
GO
ALTER TABLE [RELACAO] ADD  DEFAULT ((0)) FOR [TABELAORIGEM]
GO
ALTER TABLE [RELACAO] ADD  DEFAULT ((0)) FOR [CAMPOORIGEM]
GO
ALTER TABLE [RELACAO] ADD  DEFAULT ((0)) FOR [TABELADESTINO]
GO
ALTER TABLE [RELACAO] ADD  DEFAULT ((0)) FOR [CAMPODESTINO]
GO
ALTER TABLE [RELACAO] ADD  DEFAULT ('') FOR [CARDINALIDADEORIGEM]
GO
ALTER TABLE [RELACAO] ADD  DEFAULT ('') FOR [CARDINALIDADEDESTINO]
GO
ALTER TABLE [RESPOSTASQUESTOES] ADD  DEFAULT ((0)) FOR [CODIGOQUESTAO]
GO
ALTER TABLE [RESPOSTASQUESTOES] ADD  DEFAULT ('') FOR [DATAREGISTRO]
GO
ALTER TABLE [RESPOSTASQUESTOES] ADD  DEFAULT ('') FOR [TEXTORESPOSTA]
GO
ALTER TABLE [RESPOSTASQUESTOES] ADD  DEFAULT ('0') FOR [CERTA]
GO
ALTER TABLE [RESPOSTASUSUARIOS] ADD  DEFAULT ((0)) FOR [CODIGOUSUARIO]
GO
ALTER TABLE [RESPOSTASUSUARIOS] ADD  DEFAULT ((0)) FOR [CODIGORESPOSTA]
GO
ALTER TABLE [RESULTADOS] ADD  DEFAULT ('100') FOR [NUMEROACERTOS]
GO
ALTER TABLE [RESULTADOS] ADD  DEFAULT ('MULTIPLICAÇÃO') FOR [TIPO]
GO
ALTER TABLE [TABELA] ADD  DEFAULT ((0)) FOR [CODIGO]
GO
ALTER TABLE [TABELA] ADD  DEFAULT ((0)) FOR [PROJETO]
GO
ALTER TABLE [TABELA] ADD  DEFAULT ('') FOR [NOME]
GO
ALTER TABLE [TABELAS] ADD  DEFAULT ('') FOR [TAB]
GO
ALTER TABLE [TABELAS] ADD  DEFAULT ('') FOR [FIELD]
GO
ALTER TABLE [TABELAS] ADD  DEFAULT ('') FOR [TYPE]
GO
ALTER TABLE [TABELAS] ADD  DEFAULT ((0)) FOR [SIZE]
GO
ALTER TABLE [TABELAS] ADD  DEFAULT ((0)) FOR [PREC]
GO
ALTER TABLE [TABELAS] ADD  DEFAULT ((0)) FOR [FLAG]
GO
ALTER TABLE [TABELASMODULOS] ADD  DEFAULT ((0)) FOR [CODIGOTABELA]
GO
ALTER TABLE [TABELASMODULOS] ADD  DEFAULT ((0)) FOR [CODIGOCAMPO]
GO
ALTER TABLE [TABELASMODULOS] ADD  DEFAULT ((0)) FOR [CODIGOMODULO]
GO
ALTER TABLE [TIPOCAMPO] ADD  DEFAULT ((0)) FOR [CODIGO]
GO
ALTER TABLE [TIPOCAMPO] ADD  DEFAULT ('') FOR [NOME]
GO
ALTER TABLE [TIPOSUPORTE] ADD  DEFAULT ('') FOR [DESCRICAO]
GO
ALTER TABLE [TRADUCOES] ADD  DEFAULT ('') FOR [PALAVRAPORTUGUES]
GO
ALTER TABLE [TRADUCOES] ADD  DEFAULT ('') FOR [PALAVRAINGLES]
GO
ALTER TABLE [TRADUCOES] ADD  DEFAULT ('') FOR [CLASSEGRAMATICAL]
GO
ALTER TABLE [USUARIOCONCURSANDO] ADD  DEFAULT ('0') FOR [ADMIN]
GO
ALTER TABLE [USUARIOCONCURSANDO] ADD  DEFAULT (getdate()) FOR [created]
GO
ALTER TABLE [USUARIOCONCURSANDO] ADD  DEFAULT ('0') FOR [BOT]
GO
ALTER TABLE [USUARIOSCRUDFORMS] ADD  DEFAULT ('') FOR [LOGIN]
GO
ALTER TABLE [USUARIOSCRUDFORMS] ADD  DEFAULT ('') FOR [SENHA]
GO
ALTER TABLE [USUARIOSCRUDFORMS] ADD  DEFAULT ('0') FOR [ADMINISTRADOR]
GO
ALTER TABLE [USUARIOSCRUDFORMS] ADD  DEFAULT ('0') FOR [DESENVOLVEDOR]
GO
ALTER TABLE [USUARIOSCRUDFORMS] ADD  DEFAULT ('') FOR [EMAIL]
GO
ALTER TABLE [USUARIOSCRUDFORMS] ADD  DEFAULT ((-1)) FOR [USUARIOPAI]
GO
ALTER TABLE [VEICULOSFORDEV] ADD  DEFAULT ('') FOR [MARCA]
GO
ALTER TABLE [VEICULOSFORDEV] ADD  DEFAULT ('') FOR [MODELO]
GO
ALTER TABLE [VEICULOSFORDEV] ADD  DEFAULT ('') FOR [ANO]
GO
ALTER TABLE [VEICULOSFORDEV] ADD  DEFAULT ('') FOR [RENAVAM]
GO
ALTER TABLE [VEICULOSFORDEV] ADD  DEFAULT ('') FOR [PLACAVEICULO]
GO
ALTER TABLE [VEICULOSFORDEV] ADD  DEFAULT ('') FOR [COR]
GO
ALTER TABLE [VERBOCONJUGADO] ADD  DEFAULT ('') FOR [VERBO]
GO
ALTER TABLE [VERBOCONJUGADO] ADD  DEFAULT ('') FOR [PRESENTE]
GO
ALTER TABLE [VERBOCONJUGADO] ADD  DEFAULT ('') FOR [PRETERITOIMPERFEITO]
GO
ALTER TABLE [VERBOCONJUGADO] ADD  DEFAULT ('') FOR [PRETERITOPERFEITO]
GO
ALTER TABLE [VERBOCONJUGADO] ADD  DEFAULT ('') FOR [PRETERITOMAISQUEPERFEITO]
GO
ALTER TABLE [VERBOCONJUGADO] ADD  DEFAULT ('') FOR [FUTURODOPRESENTE]
GO
ALTER TABLE [VERBOCONJUGADO] ADD  DEFAULT ('') FOR [FUTURODOPRETERITO]
GO
ALTER TABLE [VERBOCONJUGADO] ADD  DEFAULT ('') FOR [PRONOME]
GO
ALTER TABLE [VERBOS] ADD  DEFAULT ('') FOR [PALAVRA]
GO
ALTER TABLE [BIOMAS]  WITH CHECK ADD FOREIGN KEY([IDUSUARIO])
REFERENCES [USUARIOS] ([ID])
GO
ALTER TABLE [IMAGENSBIOMA]  WITH CHECK ADD FOREIGN KEY([IDBIOMA])
REFERENCES [BIOMAS] ([ID])
GO
ALTER TABLE [IMAGENSBIOMA]  WITH CHECK ADD FOREIGN KEY([IDUSUARIO])
REFERENCES [USUARIOS] ([ID])
GO
ALTER TABLE [IMAGENSPLANTA]  WITH CHECK ADD FOREIGN KEY([IDPLANTA])
REFERENCES [PLANTAS] ([ID])
GO
ALTER TABLE [IMAGENSPLANTA]  WITH CHECK ADD FOREIGN KEY([IDUSUARIO])
REFERENCES [USUARIOS] ([ID])
GO
ALTER TABLE [PLANTAS]  WITH CHECK ADD FOREIGN KEY([IDBIOMA])
REFERENCES [BIOMAS] ([ID])
GO
ALTER TABLE [PLANTAS]  WITH CHECK ADD FOREIGN KEY([IDUSUARIO])
REFERENCES [USUARIOS] ([ID])
GO
ALTER TABLE [RESPOSTASQUESTOES]  WITH CHECK ADD FOREIGN KEY([CODIGOQUESTAO])
REFERENCES [QUESTOES] ([CODIGO])
GO
