CREATE TABLE [RESULTADOS] (
    [NOME]          VARCHAR (100) NOT NULL,
    [TEMPO]         VARCHAR (20)  NOT NULL,
    [NUMEROACERTOS] VARCHAR (10)  DEFAULT ('100') NOT NULL,
    [DATAINSERCAO]  VARCHAR (20)  NULL,
    [TIPO]          VARCHAR (100) DEFAULT ('MULTIPLICAÇÃO') NOT NULL
);

