CREATE TABLE [USUARIOS] (
    [ID]    INT          NOT NULL,
    [LOGIN] VARCHAR (50) NOT NULL,
    [PASS]  VARCHAR (12) NOT NULL,
    [NOME]  VARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    UNIQUE NONCLUSTERED ([LOGIN] ASC)
);

